name: BankPlugin
version: '${version}'

main: com.axhislmc.bankPlugin.BankPlugin
api-version: '1.21'
load: POSTWORLD

libraries:
  - com.zaxxer:HikariCP:6.2.1

commands:
  bank:
    description: Bank Plugin System to manage the Economy of your Server.